install.packages("ggfortify")
install.packages("rgl")
install.packages("ape")
install.packages("RColorBrewer")
install.packages('ape')
install.packages("tree")
install.packages("rpart.plot")
install.packages("randomForest")
install.packages("modelr")
install.packages('factoextra')
install.packages("rms")
library(rms)
library(factoextra)
library(modelr)
library(randomForest)
library(tree)
library(rpart)
library(rpart.plot)
library(ggplot2)
library(ape)
library(RColorBrewer)
library(ape)
library(rgl)
library(data.table)
library(dplyr)
library(reshape)
library(reshape2)
library(ggplot2)
library(ggfortify)
library(gplots)
library(gridExtra)
library(fmsb)
library(corrplot)
library(corrgram)
library(caTools)
library(RColorBrewer)
library(ggradar)
library(tidytext)
library(tidyverse)
library(highcharter)
library(plotly)
library(janitor)
library(GGally)
library(factoextra)


# Palette Color
palette.col.long = c("#FF4933","#FF8633","#FFBB33","#FFE633","#D7FF33","#99FF33","#52FF33","#33FF86","#33FFD1",
                     "#33D4FF","#339FFF","#336BFF","#3358FF","#5233FF","#8033FF","#B233FF","#FF33C4",
                     "#FF3396")
palette.col.short = palette.col.long[c(1,4,7,10,12,17)]

